### ISSUE TITLE
[Feature request] Use data in route

### ISSUE THREAD

**Issue by ozooxo** [nuxt-community/router-extras-module#87]
Right now I can 

```
<router>
  {
    name: 'my customized name'
  }
</router>
```

Wonder if it is easy for me to inject name from `data`, e.g.

```
<router>
  {
    name: this.mySpecialName
  }
</router>

<script>
export default {
  data() {
    return {
      mySpecialName: 'my customized name'
    };
  }
}
</script>
```

and potentially mount `mySpecialName` by an API call?

**Comment by farnabaz** [comment]
Unfortunately, this is impossible because of router limitations. The module loads `router` block of  all pages and modify routes list in `.nuxt/router.js` directory.
Also, the page component loads after moving to the new route, because of that, creating dynamic naming are impossible.

If you have any further questions feel free to reopen the issue

**Comment by farzadso** [comment]
Nice explanmation @farnabaz
